version: "3.8"
services:
  user-service:
    build: ./services/user-service
    container_name: user-service
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - ./services/user-service/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
