version: "3.8"
services:
  user-service:
    build: ./services/user-service
    container_name: user-service
    restart: always
    ports:
      - "8001:8001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/usersdb
      - NODE_ENV=production
      - PORT=8001
      - JWT_SECRET=19859c935994709d96e12e0739e566e9
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
